# Generated by Django 3.2 on 2025-08-04 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregisteredservice',
            name='description',
            field=models.TextField(blank=True, help_text="Provider's description of their service offering"),
        ),
        migrations.AddField(
            model_name='userregisteredservice',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether provider is currently accepting bookings for this service'),
        ),
        migrations.AddField(
            model_name='userregisteredservice',
            name='provider_price',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text="Provider's custom price for this service", max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProviderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1 to 5 stars')),
                ('review', models.TextField(blank=True, help_text="Customer's review of the service")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='bookings.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider_ratings',
                'unique_together': {('provider', 'customer', 'booking')},
            },
        ),
    ]
