# Generated by Django 3.2 on 2025-08-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20250804_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('provider', 'Service Provider')], max_length=20, null=True),
        ),
    ]
