# Generated by Django 3.2 on 2025-08-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.TextField(blank=True, help_text='Service address where the work will be performed', max_length=500),
        ),
    ]
