# Generated by Django 3.2 on 2025-08-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_provideravailability_provideroffday'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubcategory',
            name='duration_hours',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='Service duration in hours', max_digits=3),
        ),
    ]
