# Generated by Django 3.2 on 2025-08-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_add_service_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('provider', 'Service Provider'), ('system', 'System (Auto-cancelled)')], max_length=20, null=True),
        ),
    ]
