# Generated by Django 3.2 on 2025-08-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_add_system_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text="Reason for cancellation (e.g., 'Customer requested cancellation', 'Service provider unavailable', 'Automatically cancelled due to expiry')", max_length=500, null=True),
        ),
    ]
