# Generated by Django 3.2 on 2025-09-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_add_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerrating',
            name='provider_response',
            field=models.TextField(blank=True, help_text="Provider's response to the review"),
        ),
        migrations.AddField(
            model_name='providerrating',
            name='response_date',
            field=models.DateTimeField(blank=True, help_text='When the provider responded', null=True),
        ),
    ]
